SR-6: add-input
SoftRyzen-internship/skillryzen pull request #10
Opened 2023-02-23 13:33 UTC by vitakostiuk

2023-02-23 13:34 UTC, Kretsul-Vitaliy approved these changes

2023-02-23 17:22 UTC, Vlad-Moskalenko requested changes
https://www.loom.com/share/1c8d23bbe63e4628b12beb966973afd0

2023-02-24 10:16 UTC, vitakostiuk commented
правки внесла

2023-02-24 10:50 UTC, Vlad-Moskalenko approved these changes

2023-02-24 10:55 UTC, dykyys approved these changes

2023-02-24 10:55 UTC, merged