Feature/sr 7 add buttons
SoftRyzen-internship/skillryzen pull request #11
Opened 2023-02-23 15:24 UTC by Shynal-Nazar

Додає першу частину кнопок зі стилізацією

2023-02-23 16:00 UTC, Kretsul-Vitaliy approved these changes

2023-02-23 17:36 UTC, Vlad-Moskalenko requested changes
https://www.loom.com/share/00d50fafce3d4bf0ae1bd656a9f17999

2023-02-24 11:17 UTC, Kretsul-Vitaliy approved these changes

2023-02-24 11:22 UTC, Vlad-Moskalenko approved these changes

2023-02-24 11:33 UTC, dykyys approved these changes

2023-02-24 11:33 UTC, merged