SR-40: Add Steps
SoftRyzen-internship/skillryzen pull request #13
Opened 2023-02-23 16:36 UTC by vitakostiuk

2023-02-23 17:55 UTC, Vlad-Moskalenko requested changes
https://www.loom.com/share/ae40a88d2f1b4ffd8ed891cd1c713173

2023-02-24 09:31 UTC, vitakostiuk commented
Внесла правки по стилям

2023-02-24 10:24 UTC, Kretsul-Vitaliy approved these changes

2023-02-24 10:56 UTC, Vlad-Moskalenko approved these changes

2023-02-24 11:38 UTC, dykyys approved these changes

2023-02-24 11:38 UTC, merged