SR-15: add-popup
SoftRyzen-internship/skillryzen pull request #9
Opened 2023-02-23 13:02 UTC by vitakostiuk

2023-02-23 13:13 UTC, Kretsul-Vitaliy reviewed
Додай будь ласка в variable.scss новий колір і заміни на переміну (background: #121533;color: #3653f2;)

2023-02-23 13:37 UTC, vitakostiuk commented
змінила кольори на змінні

2023-02-23 14:10 UTC, Kretsul-Vitaliy approved these changes

2023-02-23 17:02 UTC, Vlad-Moskalenko requested changes
https://www.loom.com/share/df67ba40e48f46ac9e43963d407ffc10
і бордер-боттом додай будь-ласка, бо щось не побачив
![image](https://user-images.githubusercontent.com/94741971/220978981-b5666405-6bb0-44b4-ae08-53632b43f6dd.png)

2023-02-24 10:48 UTC, vitakostiuk commented
внесла правки

2023-02-24 10:52 UTC, Vlad-Moskalenko approved these changes

2023-02-24 10:55 UTC, Vlad-Moskalenko approved these changes

2023-02-24 11:13 UTC, Kretsul-Vitaliy approved these changes

2023-02-24 11:34 UTC, dykyys approved these changes

2023-02-24 11:34 UTC, merged